### ISSUE TITLE
Not able to use same abstract record for multiple fields

### ISSUE THREAD

**Issue by raghavgarg1257** [salsify/avro-builder#44]
I have a schema file, in which I have two fields having the same schema, `array of records`
```rb
    optional :categories, :array, items: :name_image_hash
    optional :cart_images, :array, items: :name_image_hash
```

`name_image_hash` looks like
```rb
record "name_image_hash" do
  required :url, :string
  required :name, :string
  abstract true
end
```

and it is generating schema like
```json
{
    "name": "cart_images",
    "type": [
        "null",
        {
            "type": "array",
            "items": {
                "type": "record",
                "name": "name_image_hash",
                "fields": [
                    {
                        "name": "url",
                        "type": "string"
                    },
                    {
                        "name": "name",
                        "type": "string"
                    }
                ]
            }
        }
    ],
    "default": null
},
{
    "name": "categories",
    "type": [
        "null",
        {
            "type": "array",
            "items": "name_image_hash"
        }
    ],
    "default": null
}
```
`cart_images` rendered properly, but `categories` doesn't.

I am doing something wrong, or is it a bug ??

Earlier, I wanted to do this inline, but I am not able to get the right syntax.

**Comment by tjwp** [comment]
I believe that the generated schema is correct. The best test is that it can be parsed using an Avro library. This would be `Avro::Schema.parse(schema_string)` using the Avro Ruby library.

The first reference to the type (`name_image_hash`) contains the full type definition and then subsequent references just use the type name.

I would define this as:

```ruby
  record "name_image_hash" do
    required :url, :string
    required :name, :string
  end

  record "test" do
    optional :categories, :array, items: :name_image_hash
    optional :cart_images, :array, items: :name_image_hash
  end
```

You don't need the `abstract: true` option unless it is the last/only definition in a file.

I tried to figure out a way to inline the definition for the array items, but couldn't come up with a way with the current library. That might be considered a bug with avro-builder, but it could also be argued that the support for multiple definitions in a single file (like the above) or referencing definitions in other files keeps the overall definition simpler. And the result is the same -- the type definition gets correctly inlined in the generated Avro schema.

**Comment by raghavgarg1257** [comment]
For the above schema, I was earlier using `Avro::Schema.real_parse(schema_object)`  and it is failing with error trace

> `Avro::UnknownSchemaError: "name_image_hash" is not a schema we know about.`

but `Avro::Schema.parse(schema_string)` is passing for the same schema.


Below given is the source code for `Avro::Schema.parse` method and calling `Avro::Schema.real_parse(schema_object, {})` is giving me the desired result.
```
def self.parse(json_string)
  real_parse(MultiJson.load(json_string), {})
end
```
Although, I am not sure what is the use of the second argument here or what does it represent.

Anyway, thanks for the help, it is not a bug in `avro-builder`, closing issue.
