### ISSUE TITLE
how to make avro-builder and avro_turf cooperate?

### ISSUE THREAD

**Issue by steveburkett** [salsify/avro-builder#50]
When i build a dsl like 

```
namespace 'org.openstax.interactions'

record :nudged do
  required :user_uuid, :string 
  ...
```

it creates avsc (in ./avro/schema/nudged.avsc) like this 
```
{
  "type": "record",
  "name": "nudged",
  "namespace": "org.openstax.interactions",
  "fields": [
    {
      "name": "user_uuid",
```

However, using the schema store from avro_turf, setting the schema store:

```
        AvroTurf::Messaging.new(
          registry_url: 'http://localhost:8081/',
          schemas_path: 'avro/schema'
        )
```

This fails to work when i try to encode:

```
AvroTurf::Messaging.new(...).encode(data, schema_name: "org.openstax.interactions.nudged")
```

due to this error
```
    "exception": "#<AvroTurf::SchemaNotFoundError: could not find Avro schema at `avro/schema/org/openstax/interactions/nudged.avsc'>",
```

Is there a way to tell avro-builder to build the schema in directory structure that avroturf expects, or to tell avroturf to look for schemas in the way avro-builder outputs? 

thanks!!

**Comment by tjwp** [comment]
The easiest way to handle this is to store the dsl file in a directory structure that matches the namespace:

`avro/dsl/org/openstax/interactions/nudged.rb`

Then the generated avsc file should be created at a location that matches what the avro_turf schema store expects.
