### ISSUE TITLE
can certain file extensions be skipped in the dsl rake task generation

### ISSUE THREAD

**Issue by steveburkett** [salsify/avro-builder#51]
Is there a way to have avro-builder skip certain file name masks (like *_swagger.rb) when it's generating avsc files? 

I ask because i'd like to keep other (related) files side by side w/ the foobar.rb avro dsl file.  like foobar_swagger.rb) 

thanks!

**Comment by tjwp** [comment]
I don't think this has come up before and there isn't currently a way to skip certain .rb files under the DSL root.

The way to implement this is probably to add another option (`exclude_pattern`?) that can be configured for the [AvroGenerateTask](https://github.com/salsify/avro-builder/blob/master/lib/avro/builder/rake/avro_generate_task.rb), and then skip matching files if this is configured.

Do you want to submit a PR that makes this change?
