### ISSUE TITLE
how to customize location of dsls for the rake task? 

### ISSUE THREAD

**Issue by steveburkett** [salsify/avro-builder#52]
Hi there, 

How do i get the rake task to find DSLs under a Rails.root directory called 'oxavro'?   i cant get this to work. 

e.g., i put this 
```
Avro::Builder.add_load_path('oxavro/dsl')
```
inside an initializer, but still not working. i think this gem is still using Rails.root/avro as the top level dir.

**Comment by jturkel** [comment]
`Avro::Builder.add_load_path` is only used to configure the search path for importing named types in DSL files. It does not configure the root directory for the top level DSL files themselves. There's currently no global setting to change the DSL root but you can do this on a per-rake task basis:

```ruby
# In lib/tasks/avro.rake
require 'avro/builder/rake/avro_generate_task'
Avro::Builder::Rake::AvroGenerateTask.new(name: :generate_ox, dependencies: %i(environment)) do |t|
  t.root = "#{Rails.root}/oxavro/dsl"
end
```
This isn't a configuration we've tested so you might hit some unexpected issues but PRs are always welcome :) Hope that helps.
