### ISSUE TITLE
Generated schema doesn't pretty print

### ISSUE THREAD

**Issue by jturkel** [salsify/avro-builder#58]
#56 introduced [mutli_json](https://github.com/intridea/multi_json) which broke pretty printing of generated schemas in applications that include Rails but not [oj](https://github.com/ohler55/oj) or[Yajl](https://github.com/brianmario/yajl-ruby). There appears to be something about the Rails dependency that causes the MultiJson JSON gem adapter not to support pretty printing. Here's a reproducible test case:

```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  # gem 'oj'
  # gem 'yajl-ruby'
  gem 'multi_json'
  gem 'rspec'
  # Tests pass when Rails is not present
  gem 'rails'
end

require 'rspec/autorun'
require 'multi_json'

describe do
  let(:data) do
    { foo: { bar: 'baz' } }
  end

  let(:pretty_data) do
    "{\n  \"foo\": {\n    \"bar\": \"baz\"\n  }\n}"
  end

  it "pretty prints" do
    puts "Using adapter #{MultiJson.adapter}"
    expect(MultiJson.dump(data, pretty: true)).to eq(pretty_data)
  end
end
```

**Comment by tjwp** [comment]
@jturkel Thoughts on how we should address this? Previously `JSON` was being used, and assumed to be loaded. Instead of requiring and having a dependency on `multi_json`, we could require `json`?

**Comment by jturkel** [comment]
@tjwp - It looks like the problem is ActiveSupport's patching of [to_json](https://github.com/rails/rails/blob/6-1-stable/activesupport/lib/active_support/core_ext/object/json.rb#L37) doesn't properly propagate the pretty formatting options multi_json passes [here](https://github.com/intridea/multi_json/blob/master/lib/multi_json/adapters/json_common.rb#L17). Here's a minimal reproducible test case:

```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  gem 'multi_json'
  gem 'rspec'
  gem 'activesupport', '~> 6.1.0'
end

require 'rspec/autorun'
require 'multi_json'
require 'active_support/json'

describe do
  let(:data) do
    { foo: { bar: 'baz' } }
  end

  let(:pretty_data) do
    "{\n  \"foo\": {\n    \"bar\": \"baz\"\n  }\n}"
  end

  it "pretty prints with multi_json" do
    puts "Using adapter #{MultiJson.adapter}"
    expect(MultiJson.dump(data, pretty: true)).to eq(pretty_data)
  end
end
```
For now I think we should rollback adding the `multi_json` dependency and instead require `json`.
